# Build the Go Binary.
FROM golang:1.17 as build_service
ENV CGO_ENABLED 0
ARG BUILD_REF

# RUN mkdir /service
# COPY go.* /service/
# WORKDIR /service
# RUN go mod download
# Copy the source code into the container.
COPY . /service
RUN ls

# Build the service binary.
WORKDIR /service
RUN go build -ldflags "-X main.build=${BUILD_REF}"

# Run the Go Binary in Alpine.
FROM alpine:3.15
ARG BUILD_DATE
ARG BUILD_REF
COPY --from=build_service /service/myservice /service/service
WORKDIR /service
CMD ["./service"]

LABEL org.opencontainers.image.created="${BUILD_DATE}" \
      org.opencontainers.image.title="sales-api" \
      org.opencontainers.image.authors="William Kennedy <bill@ardanlabs.com>" \
      org.opencontainers.image.source="https://github.com/ardanlabs/service/app/sales-api" \
      org.opencontainers.image.revision="${BUILD_REF}" \
      org.opencontainers.image.vendor="Ardan Labs"
